# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_wishlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.CommaSeparatedIntegerField(default='', max_length=254),
        ),
    ]
