# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-14 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_auto_20200613_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product_list',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
