# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-19 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
