# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200619_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='county',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postcode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street_address2',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
