# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-19 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_sent',
            field=models.BooleanField(default=False),
        ),
    ]
