# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
