# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20200629_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
