# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20200629_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
