# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-21 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity_list',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
