# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-21 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_quantity_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity_list',
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_list',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
