# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200621_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
