# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_developed',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='product',
            name='fruit',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='ordered_pcs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
