# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200618_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='use',
            field=models.CharField(choices=[('eat', 'eat'), ('cook', 'cook')], default='eat', max_length=254),
        ),
    ]
