# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-19 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200618_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='use',
            field=models.CharField(choices=[('eat', 'eat'), ('cook', 'cook')], default='', max_length=254),
        ),
    ]
