# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200619_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fruit',
            field=models.CharField(choices=[('apple', 'apple'), ('pear', 'pear')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='use',
            field=models.CharField(choices=[('eat', 'eat'), ('cook', 'cook')], default='', max_length=10),
        ),
    ]
